### ISSUE TITLE
Reduced-size encoded fields fails interpretation

### ISSUE THREAD

**Issue by isage** [calmh/ipfix#12]
I'm not sure why, but uint64 fields (like octetDeltaCount/packetDeltaCount) are most of the time come as 4 bytes instead of 8, so interpreter thinks that the field is corrupted and returns them as array of bytes.
This also happens with uint32 data types like ingressInterface/egressInterface where there's two bytes instead of four.

**Comment by calmh** [comment]
Yeah, that sounds like a bug.

**Comment by calmh** [comment]
(Relevant spec section: 6.2 reduced size encoding)

**Comment by calmh** [comment]
If you could attach a pcap of such data that would be helpful for testing - template plus at least one data packet.

**Comment by isage** [comment]
Sure. https://transfer.sh/12YcZw/ipfix.pcap
