### ISSUE TITLE
the builtin dictionary should be generated from the ipfix xml file

### ISSUE THREAD

**Issue by georgmu** [calmh/ipfix#2]
Currently, the builtin dictionary is generated by downloading and parsing the RFC.

The better way would be to generate the dictionary using the ipfix.xml file provided by iana ( http://www.iana.org/assignments/ipfix/ipfix.xml ).

This file is being updated on changes and defines a lot more elements than the RFC.

If you wish, I could write a script which generates builtin-dictionary.go from this xml file.

For example, openvswitch uses the same file to generate some C macros, see  https://github.com/openvswitch/ovs/blob/master/ofproto/ipfix-gen-entities .

**Comment by calmh** [comment]
Neat, I didn't know that existed. Yes please if you feel up to it, please do replace the current RFC-parsing script with one that uses the XML instead.

**Comment by calmh** [comment]
(Implemented)
